accent = "#61d6d6"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#0078d7"
selection_foreground = "#ffffff"
selection_background = "#005a9e"

color0 = "#0c0c0c"
color1 = "#c50f1f"
color2 = "#13a10e"
color3 = "#c19c00"
color4 = "#0037da"
color5 = "#881798"
color6 = "#3a96dd"
color7 = "#cccccc"
color8 = "#767676"
color9 = "#e74856"
color10 = "#16c60c"
color11 = "#f9f1a5"
color12 = "#3b78ff"
color13 = "#b4009e"
color14 = "#61d6d6"
color15 = "#f2f2f2"
